### PR TITLE
Soilwat co2 effects

### PR DESCRIPTION
**Pull request by dschlaep**

### CODE REVIEW

**Comment by dschlaep** [comment]
I created this pull request so that I can comment.

**Comment by dschlaep** [comment]
Commenting on last available commit 050dfbbe68dc8a43833411b96b745d442512c896:

- SW_Carbon.h
    * 'RCP' should be renamed to 'scenario' or similar and it must be a character string, e.g., "RCP85", "SRES A2", "SSP5-3.4-OS-Ext".
    * The currently hard-coded value of 2010 to distinguish between past and future should be turned into an input a0.
    * Why are the implemented differences past and future CO2-effects? They all come from the same continuous time-series input.
    * It may make sense to have this inputted past/future year 'a0' the year where c->co2_multipliers[i][a0] = 1.0 per definition. Because then the input biomass would be the simulated biomass of that year a0.

- SW_Control.c
    *  Yearly updates of CO2-effects to biomass: this is implemented by calling 'SW_VPD_init()' by function '_begin_year()'. The function 'SW_VPW_init()', however, includes calculations which are not dependent on the CO2-effects, i.e., the monthly interpolation of litter, pct_live, and lai_conv. They should be in a separate function that is indeed only called at the beginning. E.g., 'SW_VPD_init()' and 'SW_VPW_update()' which does the yearly updates.

**Comment by dschlaep** [comment]
Commenting on last available commit 050dfbbe68dc8a43833411b96b745d442512c896:
- SW_VegProd.h
    * The currently implemented CO2-effects do not distinguish between plant functional types, particularly the scaling equations: c1 * ppm ^ c2 uses the same coefficient values for all  types, i.e., the inputs `co2_biomass_1`, `co2_biomass_2`, `co2_stomatal_1`, `co2_stomatal_2` are defined in `struct SW_VEGPROD` and not `struct VegType`
    * There appears a considerable body of evidence in the literature that different plant types (e.g., C3 vs. C4 grasses; trees vs. grasses) may respond differently to increasing ambient CO2 concentrations. Even if we currently do not have sufficient data to estimate c1 and c2 for each type, I believe we should get the code ready to do that.

**Comment by Zachary-Kramer** [comment]
Caitlin's email response:

> Hi Daniel,
>
> Thanks for taking the time to look through the code and figures.
>
> In regards to the implementation difference between past and future CO2 effects, I am uncertain. I agree with you that hypothetically the effects should be applied the same no matter the time period. Perhaps, Zach saw a reason for this when he was writing was the code. I have now included him in this e-mail chain and have addressed the issue to him on Git.
> 
> Yes, I think that CO2 effects vary by PFT. The equations in the model for both WUE and biomass come from the spreadsheet attached below. The equations are the best fit of the points established from a literature review, which encompass multiple PFTs. Based on the info in the spreadsheet, it seems there aren't enough points to establish a strong fit for each PFT though. John can answer this more precisely. 
> 
> Thanks again!,
> Caitlin

**Comment by Zachary-Kramer** [comment]
Hi Daniel,

I appreciate the feedback. I want to be clear that this branch is still a work in progress, is not ready to be merged, and still needs things done before a full code review.

> 'RCP' should be renamed to 'scenario' or similar and it must be a character string, e.g., "RCP85", "SRES A2", "SSP5-3.4-OS-Ext".

I agree, it should be designed this way to support more scenarios, though this specific support is not within our original scope, which is supporting RCP85. While I should have designed this better off the bat, if we have time constraints it will have to be delayed into a future enhancement.

> The currently hard-coded value of 2010 to distinguish between past and future should be turned into an input a0.

> Why are the implemented differences past and future CO2-effects? They all come from the same continuous time-series input.

> It may make sense to have this inputted past/future year 'a0' the year where c->co2_multipliers[i][a0] = 1.0 per definition. Because then the input biomass would be the simulated biomass of that year a0.

For context: 
* The hard-coded value of 2010 is based off of our definitions of historical (<= 2010) and future (> 2010).
* Caitlin requested that we be able to enable/disable the effects based on these definitions. 
* Changing this to custom input changes our definition of this functionality. 
    * For instance, it would no longer be a "Historical" flag in the experimental design, but rather something along the lines of "LessThan". 

I'm not against this idea, I'm just providing context for why it is this way. Again, if we have time constraints this will have to become a future enhancement, as it is outside of the original scope.

> It may make sense to have this inputted past/future year 'a0' the year where c->co2_multipliers[i][a0] = 1.0 per definition. Because then the input biomass would be the simulated biomass of that year a0.

I am not completely understanding your explanation. Why do we want the input biomass to be the simulated biomass of year a0? If you are suggesting that this be the base point, where biomass multipliers before it are <1 and after it are >1, that would change the equation, wouldn't it? Sorry, I'm just a bit confused.

> Yearly updates of CO2-effects to biomass: this is implemented by calling 'SW_VPD_init()' by function '_begin_year()'. The function 'SW_VPW_init()', however, includes calculations which are not dependent on the CO2-effects, i.e., the monthly interpolation of litter, pct_live, and lai_conv. They should be in a separate function that is indeed only called at the beginning. E.g., 'SW_VPD_init()' and 'SW_VPW_update()' which does the yearly updates.

I agree. The current approach just has a very small performance effect and is tightly coupled, correct? In which case this should be a lower priority enhancement.

**Comment by Zachary-Kramer** [comment]
@dschlaep Could you do another iteration for this review? I have some recent changes, but nothing that significant

**Comment by dschlaep** [comment]
Sure, I will. Give me a few days.

Thanks!

**Comment by dschlaep** [comment]
Good job!

I opened four new issues (of which I consider only 2 high priority). Please consider them. 

Please revert the testing folder to our old default values (plus enable both the CO2-effects).

**Comment by Zachary-Kramer** [comment]
Thanks for the review! I'm off work this week and next week because I'm moving to Germany, so I won't fix these issues until after then. I'll revert the testing folder as well.

**Comment by dschlaep** [comment]
Unit tests (when debug statements in function `calculate_CO2_multipliers` are turned on) of commit ea720d03a048f326bf6a061e4f05d3f95707957c pass on my local computer and on travis-ci, but fail on appveyor-ci during `CarbonTest.CO2multipliers`:

travis-ci:
```
./sw_test
[==========] Running 7 tests from 4 test cases.
[----------] Global test environment set-up.
...
[ RUN      ] CarbonTest.CO2multipliers
Shrub: use1: bio_mult[1980] = 0.976 / coeff1 = 0.127 / coeff2 = 0.350 / ppm = 338.36
Shrub: use1: bio_mult[1981] = 0.977 / coeff1 = 0.127 / coeff2 = 0.350 / ppm = 339.73
Shrub: use1: bio_mult[1982] = 0.978 / coeff1 = 0.127 / coeff2 = 0.350 / ppm = 340.79
...
[==========] 7 tests from 4 test cases ran. (117 ms total)
[  PASSED  ] 7 tests.
```

appveyor-ci:
```
./sw_test
[==========] Running 7 tests from 4 test cases.
[----------] Global test environment set-up.
...
[ RUN      ] CarbonTest.CO2multipliers
Shrub: use1: bio_mult[1980] = 0.000 / coeff1 = 0.000 / coeff2 = 0.000 / ppm = 338.36
Shrub: use1: bio_mult[1981] = 0.000 / coeff1 = 0.000 / coeff2 = 0.000 / ppm = 339.73
Shrub: use1: bio_mult[1982] = 0.000 / coeff1 = 0.000 / coeff2 = 0.000 / ppm = 340.79
...
test/test_SW_Carbon.cc:111: Failure
Expected: (v->forb.co2_multipliers[0][year]) > (0.), actual: 0 vs 0
test/test_SW_Carbon.cc:112: Failure
Expected: (v->grass.co2_multipliers[0][year]) > (0.), actual: 0 vs 0
...
[----------] Global test environment tear-down
[==========] 7 tests from 4 test cases ran. (48 ms total)
[  PASSED  ] 6 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CarbonTest.CO2multipliers
 1 FAILED TEST
```

**Comment by dschlaep** [comment]
```
[ RUN      ] CarbonTest.CO2multipliers
coeff1 = 0.000 / coeff2 = 0.000
```
in appveyor-ci and not travis-ci because the order of unit test execution differs.
On travis-ci: `CarbonTest > VegTest`
On appveyor-ci: `VegTest > CarbonTest`

**Comment by dschlaep** [comment]
That did the trick! Unit tests have to carefully reset global states!

**Pull request merged**
